key_value_api="AIzaSyC2cVBQ5XGnjX95JfFnbJhwHy5ay5LbYEk"

[api]
API_CAMPODIGITAL_RENDER= "https://campo-digital-cesde.onrender.com"
API_CAMPODIGITAL_SWAGGER= "http://localhost:8080"
user = "SCORREA"
pass = "980522Sc"